import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

export const runtime = "nodejs";

function generateFallbackQuoteNumber(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  const t = String(Date.now()).slice(-4);
  return `LT-${y}${m}${day}-${t}`;
}

function asNumber(v: unknown, fallback = 0): number {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function pick<T>(obj: any, keys: string[], fallback: T): T {
  for (const k of keys) {
    if (obj && obj[k] !== undefined && obj[k] !== null) return obj[k] as T;
  }
  return fallback;
}

async function getNextQuoteNo(): Promise<number | null> {
  // If you have a DB function `next_quote_number()` return bigint/int
  try {
    const { data, error } = await supabaseAdmin.rpc("next_quote_number");
    if (error) return null;
    const n = Number(data);
    return Number.isFinite(n) ? n : null;
  } catch {
    return null;
  }
}

function formatQuoteNumberFromNo(quoteNo: number): string {
  // Example: LLT-000014
  return `LLT-${String(quoteNo).padStart(6, "0")}`;
}

export async function POST(req: Request) {
  try {
    const body: any = await req.json();
    const status = body?.status as string | undefined;
    const draft = body?.draft as any;

    if (status !== "SENT") {
      return NextResponse.json(
        { ok: false, error: "Only SENT status is supported" },
        { status: 400 }
      );
    }

    if (!draft) {
      return NextResponse.json(
        { ok: false, error: "Draft data is required in request body" },
        { status: 400 }
      );
    }

    const lines: any[] = Array.isArray(draft.lines) ? draft.lines : [];
    if (lines.length === 0) {
      return NextResponse.json(
        { ok: false, error: "At least one line is required" },
        { status: 400 }
      );
    }

    // 1) Create the quote header FIRST (quotes.quote_id is PK and generated by DB)
    const quoteNo = await getNextQuoteNo();
    const quoteNumber = quoteNo ? formatQuoteNumberFromNo(quoteNo) : generateFallbackQuoteNumber();

    const vehicleMake = pick<string | null>(draft, ["vehicle_make", "vehicleMake"], null);
    const vehicleModel = pick<string | null>(draft, ["vehicle_model", "vehicleModel"], null);
    const vehicleYear = pick<number | null>(draft, ["vehicle_year", "vehicleYear"], null);

    const vehicleText = pick<string | null>(draft, ["vehicle_text", "vehicleText"], null) ??
      [vehicleMake, vehicleModel, vehicleYear].filter(Boolean).join(" ") || null;

    const headerPayload: Record<string, any> = {
      quote_number: quoteNumber,
      quote_no: quoteNo,
      status: "SENT",
      sent_at: new Date().toISOString(),
      customer_name: pick<string | null>(draft, ["customer_name", "customerName"], null),
      customer_phone: pick<string | null>(draft, ["customer_phone", "customerPhone"], null),
      customer_email: pick<string | null>(draft, ["customer_email", "customerEmail"], null),
      vehicle_text: vehicleText,
      vehicle_make: vehicleMake,
      vehicle_model: vehicleModel,
      vehicle_year: vehicleYear,
      deposit_amount: pick<number | null>(draft, ["deposit_amount", "depositAmount"], null),
      promised_at: pick<string | null>(draft, ["promised_at", "promisedAt"], null),
      internal_notes: pick<string | null>(draft, ["internal_notes", "internalNotes"], null),
      notes: pick<string | null>(draft, ["notes"], null),
      markup_pct: pick<number>(draft, ["markup_pct", "markupPct"], 30),
      install_each: pick<number>(draft, ["install_each", "installEach"], 1000),
      extras_each: pick<number>(draft, ["extras_each", "extrasEach"], 1000),
      urgency: pick<string | null>(draft, ["urgency"], null),
      preference: pick<string | null>(draft, ["preference"], null),
    };

    const { data: quoteRow, error: quoteErr } = await supabaseAdmin
      .from("quotes")
      .insert(headerPayload)
      .select("quote_id, quote_number")
      .single();

    if (quoteErr || !quoteRow?.quote_id) {
      console.error("QUOTE INSERT ERROR:", quoteErr);
      throw new Error("Failed to create quote");
    }

    const quoteId: string = quoteRow.quote_id;

    // 2) Insert lines & items
    let minStock: number | null = null;

    for (let i = 0; i < lines.length; i++) {
      const ln = lines[i] ?? {};
      const size: string = String(pick<string>(ln, ["size"], "")).trim();
      const qty: number = asNumber(
        pick<number>(ln, ["requested_qty", "requestedQty", "quantity", "qty"], 1),
        1
      );

      if (!size) {
        // If a line has no size, skip it to avoid DB errors
        continue;
      }

      const linePayload: Record<string, any> = {
        quote_id: quoteId,
        line_no: i + 1,
        size,
        quantity: qty,
        vehicle_make: pick<string | null>(ln, ["vehicle_make", "vehicleMake"], vehicleMake),
        vehicle_model: pick<string | null>(ln, ["vehicle_model", "vehicleModel"], vehicleModel),
        vehicle_year: pick<number | null>(ln, ["vehicle_year", "vehicleYear"], vehicleYear),
        vehicle_index: pick<number | null>(ln, ["vehicle_index", "vehicleIndex"], null),
      };

      const { data: lineRow, error: lineErr } = await supabaseAdmin
        .from("quote_lines")
        .insert(linePayload)
        .select("line_id")
        .single();

      if (lineErr || !lineRow?.line_id) {
        console.error("LINE INSERT ERROR:", lineErr);
        throw new Error("Failed to insert quote line");
      }

      const lineId: string = lineRow.line_id;

      const options: any[] = Array.isArray(ln.options) ? ln.options : [];
      const includedOptions = options.filter((o) => o?.included !== false);
      if (includedOptions.length === 0) {
        throw new Error("Each line must have at least one included option");
      }

      let selectedQuoteItemId: string | null = null;

      for (let j = 0; j < includedOptions.length; j++) {
        const o: any = includedOptions[j] ?? {};

        const stock = asNumber(pick<number>(o, ["stock"], 0), 0);
        if (minStock === null) minStock = stock;
        else minStock = Math.min(minStock, stock);

        const priceEach = asNumber(pick<number>(o, ["price_each", "priceEach"], 0), 0);
        const totalTires = asNumber(
          pick<number>(o, ["total_tires", "totalTires", "total"], priceEach * qty),
          priceEach * qty
        );
        const totalWithServices = asNumber(
          pick<number>(o, ["total_with_services", "totalWithServices"], totalTires),
          totalTires
        );

        const itemPayload: Record<string, any> = {
          quote_id: quoteId,
          quote_line_id: lineId,
          line_id: lineId,
          rank: pick<number | null>(o, ["rank"], j + 1),
          provider: pick<string | null>(o, ["provider"], null),
          sku: pick<string | null>(o, ["sku"], null),
          tire_id: pick<string | null>(o, ["tire_id", "tireId"], null),
          brand: pick<string | null>(o, ["brand"], null),
          model: pick<string | null>(o, ["model"], null),
          load_speed: pick<string | null>(o, ["load_speed", "loadSpeed"], null),
          size: pick<string | null>(o, ["size"], size),
          stock,
          cost: pick<number | null>(o, ["cost", "cost_each", "costEach"], null),
          price_each: priceEach,
          total_tires: totalTires,
          total_with_services: totalWithServices,
          included: o?.included !== false,
        };

        const { data: itemRow, error: itemErr } = await supabaseAdmin
          .from("quote_items")
          .insert(itemPayload)
          .select("quote_item_id")
          .single();

        if (itemErr || !itemRow?.quote_item_id) {
          console.error("ITEM INSERT ERROR:", itemErr);
          throw new Error("Failed to insert quote item");
        }

        if (!selectedQuoteItemId) selectedQuoteItemId = itemRow.quote_item_id;
      }

      if (selectedQuoteItemId) {
        const { error: selErr } = await supabaseAdmin
          .from("quote_lines")
          .update({ selected_quote_item_id: selectedQuoteItemId })
          .eq("line_id", lineId);
        if (selErr) {
          // Non-fatal, but useful
          console.warn("Could not update selected_quote_item_id:", selErr);
        }
      }
    }

    // 3) Update quote header with min_stock (best-effort)
    if (minStock !== null) {
      const { error: uErr } = await supabaseAdmin
        .from("quotes")
        .update({ min_stock: minStock })
        .eq("quote_id", quoteId);
      if (uErr) {
        console.warn("Could not update min_stock:", uErr);
      }
    }

    return NextResponse.json({
      ok: true,
      quoteId,
      quoteNumber,
    });
  } catch (err: any) {
    console.error("QUOTE STATUS ERROR:", err);
    return NextResponse.json(
      { ok: false, error: err?.message ?? "Unknown error" },
      { status: 500 }
    );
  }
}
