-- Customers + human-friendly quote number support

create table if not exists customers (
  customer_id uuid primary key default gen_random_uuid(),
  name text,
  phone text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- normalize expectations:
-- phone should be digits only (e.g. 4421234567). email lowercase.
create unique index if not exists ux_customers_phone on customers(phone) where phone is not null;
create unique index if not exists ux_customers_email on customers(email) where email is not null;

-- Add customer_id + quote_no to quotes
alter table quotes add column if not exists customer_id uuid references customers(customer_id);
alter table quotes add column if not exists quote_no bigint generated by default as identity;

create unique index if not exists ux_quotes_quote_no on quotes(quote_no);

-- Helpful trigger to keep updated_at fresh
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_customers_updated_at on customers;
create trigger trg_customers_updated_at
before update on customers
for each row execute function set_updated_at();

-- (Optional) Disable RLS for MVP
alter table customers disable row level security;
